language: objective-c
osx_image: xcode8
env:
    global:
        - LC_CTYPE=en_US.UTF-8
        - LANG=en_US.UTF-8
    matrix:
        - DESTINATION="OS=10.0,name=iPhone 7 Plus"
        - DESTINATION="OS=8.0,name=iPhone 5"
before_install:
    - gem install xcpretty -N
script:
    - set -o pipefail
    - xcodebuild -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty
    - xcodebuild -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty
