language: objective-c
osx_image: xcode8
env:
    global:
        - LC_CTYPE=en_US.UTF-8
        - LANG=en_US.UTF-8
        - IOS_FRAMEWORK_SCHEME="Curator"
    matrix:
        - DESTINATION="OS=10.0,name=iPhone 7 Plus" SCHEME="$IOS_FRAMEWORK_SCHEME"
        # - DESTINATION="OS=8.4,name=iPhone 5"       SCHEME="$IOS_FRAMEWORK_SCHEME"
before_install:
    - gem install xcpretty -N
script:
    - set -o pipefail
    - xcodebuild -scheme "$SCHEME"  -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty
    - xcodebuild -scheme "$SCHEME"  -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO | xcpretty
after_success:
    - bash <(curl -s https://codecov.io/bash)
